# Generated by Django 4.2.30 on 2026-06-03 14:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                ("last_updated", models.DateField(blank=True, null=True)),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "services_list",
                    wagtail.fields.StreamField(
                        [
                            (
                                "service",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "icon",
                                            wagtail.blocks.CharBlock(
                                                help_text="CSS class or icon name",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PrivacyPolicyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                ("last_updated", models.DateField(blank=True, null=True)),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_subtitle", models.CharField(blank=True, max_length=500)),
                ("hero_cta_text", models.CharField(blank=True, max_length=100)),
                ("hero_cta_url", models.CharField(blank=True, max_length=500)),
                (
                    "featured_posts",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="blog.blogpage"
                    ),
                ),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "form_id",
                    models.CharField(
                        blank=True, help_text="External form identifier", max_length=100
                    ),
                ),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.CharBlock(form_classname="title"),
                            ),
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "team_members",
                    wagtail.fields.StreamField(
                        [
                            (
                                "member",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "name",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "role",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "photo",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "bio",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
