# Generated by Django 4.2.30 on 2026-06-02 11:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Author Index Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AuthorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True,
                        help_text="~155 characters. Falls back to excerpt / intro if blank.",
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's own URL.",
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        default="index, follow",
                        help_text="e.g. 'noindex, nofollow'",
                        max_length=100,
                        verbose_name="Robots directive",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to page title if blank.",
                        max_length=255,
                        verbose_name="OG title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, verbose_name="OG description"),
                ),
                (
                    "og_type",
                    models.CharField(
                        blank=True,
                        default="website",
                        help_text="e.g. website, article, profile",
                        max_length=50,
                        verbose_name="OG type",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Twitter title"
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(blank=True, verbose_name="Twitter description"),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary (large image)"),
                            ("app", "App"),
                            ("player", "Player"),
                        ],
                        default="summary_large_image",
                        max_length=30,
                        verbose_name="Twitter card type",
                    ),
                ),
                (
                    "schema_json",
                    models.TextField(
                        blank=True,
                        help_text="Paste raw JSON-LD (will be validated). Leave blank for auto-generated schema.",
                        verbose_name="JSON-LD structured data",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Job title / role"
                    ),
                ),
                ("bio", wagtail.fields.RichTextField(blank=True)),
                (
                    "short_bio",
                    models.TextField(
                        blank=True,
                        help_text="Brief bio shown in blog post bylines (max 300 chars)",
                        max_length=300,
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter / X URL"),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Personal website"),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recommended: 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="OG image",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Author photo",
                    ),
                ),
                (
                    "twitter_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Twitter image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
