# Generated by Django 4.2.30 on 2026-06-02 17:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("taxonomy", "0001_initial"),
        ("blog", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="blog_posts", to="taxonomy.category"
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Card thumbnail for listing pages.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Cover image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Hero image shown at the top of the post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Featured image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Recommended: 1200×630 px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="OG image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="twitter_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Twitter image",
            ),
        ),
    ]
