# Generated by Django 4.2.30 on 2026-06-03 14:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("images", "__first__"),
        ("tags", "0001_initial"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("intro", models.CharField(blank=True, max_length=300)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.CharBlock(form_classname="title"),
                            ),
                            ("paragraph", wagtail.blocks.RichTextBlock()),
                            ("image", wagtail.images.blocks.ImageChooserBlock()),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "language",
                                            wagtail.blocks.CharBlock(
                                                help_text="Programming language",
                                                required=False,
                                            ),
                                        ),
                                        ("code", wagtail.blocks.TextBlock()),
                                    ]
                                ),
                            ),
                            (
                                "quote",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("text", wagtail.blocks.RichTextBlock()),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                    ]
                                ),
                            ),
                            ("embed", wagtail.embeds.blocks.EmbedBlock()),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "reading_time_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Auto‑computed on save (based on body text)",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to="authors.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "blog_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_page_tags",
                        to="blog.blogpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tags.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("blog_page", "tag")},
            },
        ),
        migrations.CreateModel(
            name="BlogPageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "blog_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_page_categories",
                        to="blog.blogpage",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "unique_together": {("blog_page", "category")},
            },
        ),
        migrations.AddField(
            model_name="blogpage",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="blog_pages",
                through="blog.BlogPageCategory",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="promo_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image used for social media sharing and promo cards.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="blog_pages",
                through="blog.BlogPageTag",
                to="tags.tag",
            ),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "seo_title_custom",
                    models.CharField(
                        blank=True,
                        help_text="Override the default SEO title.",
                        max_length=255,
                    ),
                ),
                (
                    "search_description_custom",
                    models.TextField(
                        blank=True, help_text="Override the default search description."
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "promo_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image used for social media sharing and promo cards.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index",
            },
            bases=("wagtailcore.page",),
        ),
    ]
