# Generated by Django 4.2.30 on 2026-06-02 16:56

import apps.common.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralFlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "level",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "anchor_id",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional anchor slug for deep-linking (auto-generated if blank)",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.blocks.RichTextBlock(
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "ol",
                                                    "ul",
                                                    "hr",
                                                    "superscript",
                                                    "subscript",
                                                ]
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            ("rich_text", apps.common.blocks.RichTextBlock()),
                            (
                                "quote",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "quote",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.blocks.CharBlock(
                                                label="Author / source", required=False
                                            ),
                                        ),
                                        (
                                            "attribution_url",
                                            wagtail.blocks.URLBlock(
                                                label="Source URL", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("python", "Python"),
                                                    ("javascript", "JavaScript"),
                                                    ("typescript", "TypeScript"),
                                                    ("jsx", "JSX / TSX"),
                                                    ("html", "HTML"),
                                                    ("css", "CSS"),
                                                    ("bash", "Bash / Shell"),
                                                    ("json", "JSON"),
                                                    ("yaml", "YAML"),
                                                    ("sql", "SQL"),
                                                    ("go", "Go"),
                                                    ("rust", "Rust"),
                                                    ("plaintext", "Plain text"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "filename",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional filename label",
                                                required=False,
                                            ),
                                        ),
                                        ("code", wagtail.blocks.TextBlock()),
                                    ]
                                ),
                            ),
                            ("markdown", apps.common.blocks.MarkdownBlock()),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Overrides the image title for alt text",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.RichTextBlock(
                                                features=["bold", "italic", "link"],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                    ("full", "Full width"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "gallery",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "images",
                                            wagtail.blocks.ListBlock(
                                                wagtail.images.blocks.ImageChooserBlock()
                                            ),
                                        ),
                                        (
                                            "columns",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("2", "2 columns"),
                                                    ("3", "3 columns"),
                                                    ("4", "4 columns"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("embed", apps.common.blocks.VideoEmbedBlock()),
                            (
                                "youtube",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "video_id",
                                            wagtail.blocks.CharBlock(
                                                help_text="The YouTube video ID (e.g. dQw4w9WgXcQ)",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "start_time",
                                            wagtail.blocks.IntegerBlock(
                                                default=0,
                                                help_text="Start time in seconds",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "autoplay",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                        (
                                            "show_controls",
                                            wagtail.blocks.BooleanBlock(
                                                default=True, required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "button",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "label",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                        (
                                            "page",
                                            wagtail.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "style",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("primary", "Primary"),
                                                    ("secondary", "Secondary"),
                                                    ("outline", "Outline"),
                                                    ("ghost", "Ghost"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "open_in_new_tab",
                                            wagtail.blocks.BooleanBlock(
                                                default=False, required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                features=["bold", "italic", "link"],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "buttons",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "label",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "style",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "primary",
                                                                        "Primary",
                                                                    ),
                                                                    (
                                                                        "secondary",
                                                                        "Secondary",
                                                                    ),
                                                                    (
                                                                        "outline",
                                                                        "Outline",
                                                                    ),
                                                                    ("ghost", "Ghost"),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "open_in_new_tab",
                                                            wagtail.blocks.BooleanBlock(
                                                                default=False,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "background",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("white", "White"),
                                                    ("light", "Light grey"),
                                                    ("dark", "Dark"),
                                                    ("brand", "Brand colour"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "faq",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                default="Frequently Asked Questions",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "question",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "answer",
                                                            wagtail.blocks.RichTextBlock(
                                                                features=[
                                                                    "bold",
                                                                    "italic",
                                                                    "link",
                                                                    "ol",
                                                                    "ul",
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "statistics",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "stats",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "label",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "value",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="e.g. '10,000+' or '99%'",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "features",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "subtitle",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "features",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon_name",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Icon name (e.g. Heroicons slug)",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "link",
                                                            wagtail.blocks.URLBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("grid", "Grid"),
                                                    ("list", "List"),
                                                    ("alternating", "Alternating"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "testimonials",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                default="What our readers say",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "testimonials",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "quote",
                                                            wagtail.blocks.TextBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "author_name",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "author_title",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "author_image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "rating",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=5,
                                                                max_value=5,
                                                                min_value=1,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("carousel", "Carousel"),
                                                    ("grid", "Grid"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "related_content",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                default="Related Articles",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "pages",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.PageChooserBlock()
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(required=False),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.RichTextBlock(
                                                features=["bold", "italic", "link"],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "image_alt",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "buttons",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "label",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "style",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "primary",
                                                                        "Primary",
                                                                    ),
                                                                    (
                                                                        "secondary",
                                                                        "Secondary",
                                                                    ),
                                                                    (
                                                                        "outline",
                                                                        "Outline",
                                                                    ),
                                                                    ("ghost", "Ghost"),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "open_in_new_tab",
                                                            wagtail.blocks.BooleanBlock(
                                                                default=False,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                        (
                                            "layout",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("centered", "Centered"),
                                                    ("left", "Left-aligned"),
                                                    ("split", "Split (text + image)"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "background",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("white", "White"),
                                                    ("light", "Light"),
                                                    ("dark", "Dark"),
                                                    ("gradient", "Gradient"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "estimated_reading_minutes",
                    models.IntegerField(default=1, editable=False),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
